name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build Windows release
        run: |
          # Build your desktop app for Windows here
          # Replace the following command with your build command
          dotnet publish -c Release -r win-x64 --self-contained false MaidService.csproj
      - name: Upload Windows release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /path/to/windows/release
          asset_name: MaidService_windows.zip
          asset_content_type: application/zip

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build Android release
        run: |
          # Build your Android APK here
          # Replace the following command with your build command
          dotnet publish -c Release -r android-arm64 --self-contained false MaidService.Android.csproj
      - name: Upload Android release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /path/to/android/release
          asset_name: MaidService_android.apk
          asset_content_type: application/vnd.android.package-archive